name: Deploy Static Files to Pantheon

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SFTP_HOST: ${{ secrets.PANTHEON_SFTP_HOST }}
      SFTP_PORT: ${{ secrets.PANTHEON_SFTP_PORT }}
      SFTP_USERNAME: ${{ secrets.PANTHEON_SFTP_USERNAME }}
      SFTP_KEY_PATH: /tmp/id_rsa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install paramiko

      - name: Add SSH Private Key
        run: |
          echo "${{ secrets.PANTHEON_SFTP_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Upload files via SFTP
        run: python script.py
