name: Deploy Static Assets to Pantheon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Static Folder via SFTP
        uses: picodebr/copy-action@v1
        with:
          ssh_key: ${{ secrets.PANTHEON_SFTP_PRIVATE_KEY }}
          ssh_user: ${{ secrets.PANTHEON_SFTP_USERNAME }}     # e.g. dev.yoursite
          ssh_host: ${{ secrets.PANTHEON_SFTP_HOST }}         # e.g. appserver.dev-site.pantheon.io
          source: ./api-portal/static/
          destination: /code/web/sites/default/files/static
