name: Upload Static Files to Pantheon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Write RSA private key
        run: |
          echo "${{ secrets.PANTHEON_SFTP_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

      - name: Upload static files via lftp
        run: |
          lftp -u ${{ secrets.PANTHEON_SFTP_USERNAME }}, -e "
            set sftp:connect-program 'ssh -a -x -i /tmp/private_key -o StrictHostKeyChecking=no -p ${{ secrets.PANTHEON_SFTP_PORT }}'
            mirror -R api-portal/static /code/web/sites/default/files/static
            quit
          " sftp://${{ secrets.PANTHEON_SFTP_HOST }}
