name: Upload API Portal Static Files to Drupal

on:
  push:
    branches:
      - main

jobs:
  deploy-static:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: Check that static folder exists
      - name: Verify static folder exists
        run: |
          if [ ! -d "api-portal/static" ]; then
            echo "api-portal/static does not exist!"
            exit 1
          fi

      - name: Upload static via lftp
        run: |
            echo "${{ secrets.PANTHEON_SFTP_PRIVATE_KEY }}" > /tmp/private_key
            chmod 600 /tmp/private_key

            lftp -u ${{ secrets.PANTHEON_SFTP_USERNAME }}, -e "
            set sftp:connect-program 'ssh -a -x -i /tmp/private_key -o StrictHostKeyChecking=no -p ${{ secrets.PANTHEON_SFTP_PORT }}'
            mirror -R api-portal/static /code/web/sites/default/files/static
            quit
            " sftp://${{ secrets.PANTHEON_SFTP_HOST }}



 